#pragma once

// #include "online-judge/leetcode/3.h"
// #include "online-judge/leetcode/36.h"
// #include "online-judge/leetcode/37.h"
// #include "online-judge/leetcode/39.h"
// #include "online-judge/leetcode/40.h"
// #include "online-judge/leetcode/47.h"
// #include "online-judge/leetcode/68.h"
// #include "online-judge/leetcode/76.h"
// #include "online-judge/leetcode/77.h"
// #include "online-judge/leetcode/78.h"
// #include "online-judge/leetcode/79.h"
// #include "online-judge/leetcode/94.h"
// #include "online-judge/leetcode/124.h"
// #include "online-judge/leetcode/155.h"
// #include "online-judge/leetcode/165.h"
// #include "online-judge/leetcode/173.h"
// #include "online-judge/leetcode/207.h"
// #include "online-judge/leetcode/216.h"
// #include "online-judge/leetcode/212.h"
// #include "online-judge/leetcode/226.h"
// #include "online-judge/leetcode/235.h"
// #include "online-judge/leetcode/239.h"
// #include "online-judge/leetcode/313.h"
// #include "online-judge/leetcode/316.h"
// #include "online-judge/leetcode/404.h"
// #include "online-judge/leetcode/438.h"
// #include "online-judge/leetcode/502.h"
// #include "online-judge/leetcode/538.h"
// #include "online-judge/leetcode/600.h"
// #include "online-judge/leetcode/617.h"
// #include "online-judge/leetcode/637.h"
// #include "online-judge/leetcode/689.h"
// #include "online-judge/leetcode/743.h"
// #include "online-judge/leetcode/784.h"
// #include "online-judge/leetcode/787.h"
// #include "online-judge/leetcode/789.h"
// #include "online-judge/leetcode/797.h"
// #include "online-judge/leetcode/802.h"
#include "online-judge/leetcode/851.h"
// #include "online-judge/leetcode/968.h"
// #include "online-judge/leetcode/1034.h"
// #include "online-judge/leetcode/1114.h"
// #include "online-judge/leetcode/1115.h"
// #include "online-judge/leetcode/1646.h"

void TreeNodeTest();
void ConcurrencyTest();
void LeetCode();

